package platform

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/json"
	"net/http"
	"strconv"
	"time"
)

type publicCacheEntry struct {
	body            []byte
	expires         time.Time
	digest          [sha256.Size]byte
	socketPrefix    []byte
	matchID, handID string
}

// Prepare the public socket envelope once per cache fill. The payload stays
// immutable; only stream identity and sequence are appended for each recipient.
// HTTP keeps its database sequence, while sockets never expose it or decisions.
func newPublicCacheEntry(view map[string]any, expires time.Time) (publicCacheEntry, error) {
	body, err := json.Marshal(view)
	if err != nil {
		return publicCacheEntry{}, err
	}
	envelope := make(map[string]any, len(view))
	for key, value := range view {
		switch key {
		case "seq", "decision", "stream_id", "view_seq":
			continue
		}
		envelope[key] = value
	}
	payload, err := json.Marshal(envelope)
	if err != nil {
		return publicCacheEntry{}, err
	}
	matchID, _ := view["match_id"].(string)
	handID, _ := view["hand_id"].(string)
	prefix := payload[:len(payload)-1]
	if len(envelope) > 0 {
		prefix = append(prefix, ',')
	}
	return publicCacheEntry{body: body, expires: expires, digest: sha256.Sum256(body), socketPrefix: prefix, matchID: matchID, handID: handID}, nil
}

func (entry publicCacheEntry) socketFrame(stream string, seq int64) []byte {
	frame := make([]byte, 0, len(entry.socketPrefix)+len(stream)+64)
	frame = append(frame, entry.socketPrefix...)
	frame = append(frame, `"stream_id":`...)
	quoted, _ := json.Marshal(stream)
	frame = append(frame, quoted...)
	frame = append(frame, `,"view_seq":`...)
	frame = strconv.AppendInt(frame, seq, 10)
	return append(frame, '}')
}

const publicCacheTTL = 200 * time.Millisecond
const publicCacheRooms = 512

func (s *Service) invalidatePublicSnapshots() {
	s.publicMu.Lock()
	defer s.publicMu.Unlock()
	s.publicSnapshots = nil
	s.publicGeneration++
}

// Only this explicitly public path is cached. The encoded body is immutable,
// so a socket can compare its digest before allocating a recipient frame.
// A private projection can never populate, read or share this cache.
func (s *Service) cachedPublicEntry(r *http.Request, roomID string) (publicCacheEntry, error) {
	key := "spectator_discard_only@1/" + roomID
	read := func() (publicCacheEntry, bool) {
		s.publicMu.Lock()
		defer s.publicMu.Unlock()
		if entry, ok := s.publicSnapshots[key]; ok && time.Now().Before(entry.expires) {
			return entry, true
		}
		return publicCacheEntry{}, false
	}
	entry, ok := read()
	if !ok {
		value, err, _ := s.publicLoads.Do(key, func() (any, error) {
			if cached, ok := read(); ok {
				return cached, nil
			}
			s.publicMu.Lock()
			generation := s.publicGeneration
			s.publicMu.Unlock()
			ctx, cancel := context.WithTimeout(r.Context(), 2*time.Second)
			defer cancel()
			view, err := s.snapshotUncached(r.WithContext(ctx), roomID, "")
			if err != nil {
				return nil, err
			}
			entry, err := newPublicCacheEntry(view, time.Now().Add(publicCacheTTL))
			if err != nil {
				return nil, err
			}
			s.publicMu.Lock()
			defer s.publicMu.Unlock()
			if generation != s.publicGeneration {
				return nil, api(503, "VIEW_REFRESHING")
			}
			if s.publicSnapshots == nil {
				s.publicSnapshots = map[string]publicCacheEntry{}
			}
			if len(s.publicSnapshots) >= publicCacheRooms {
				oldest := ""
				var expiry time.Time
				for k, v := range s.publicSnapshots {
					if oldest == "" || v.expires.Before(expiry) {
						oldest = k
						expiry = v.expires
					}
				}
				delete(s.publicSnapshots, oldest)
			}
			s.publicSnapshots[key] = entry
			return entry, nil
		})
		if err != nil {
			return publicCacheEntry{}, err
		}
		entry = value.(publicCacheEntry)
	}
	return entry, nil
}

func (s *Service) cachedPublicSnapshot(r *http.Request, roomID string) (map[string]any, error) {
	entry, err := s.cachedPublicEntry(r, roomID)
	if err != nil {
		return nil, err
	}
	return decodePublicSnapshot(entry.body)
}

func decodePublicSnapshot(body []byte) (map[string]any, error) {
	var view map[string]any
	d := json.NewDecoder(bytes.NewReader(body))
	d.UseNumber()
	if err := d.Decode(&view); err != nil {
		return nil, err
	}
	if n, ok := view["seq"].(json.Number); ok {
		v, err := n.Int64()
		if err != nil {
			return nil, err
		}
		view["seq"] = v
	}
	return view, nil
}

// Historical projections deliberately retain stable participant references.
// Resolve account deletion at read time as well, so an older persisted name or
// a replay regenerated by a pinned rule never restores deleted display details.
func (s *Service) deletedParticipants(ctx context.Context, matchID string) (map[string]bool, error) {
	rows, err := s.pool.Query(ctx, `SELECT p.participant_id FROM platform_seats p JOIN platform_matches m ON m.room_id=p.room_id JOIN auth_users u ON u.id=p.user_id WHERE m.id=$1 AND u.status='deleted'`, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	ids := map[string]bool{}
	for rows.Next() {
		var id string
		if err = rows.Scan(&id); err != nil {
			return nil, err
		}
		ids[id] = true
	}
	return ids, rows.Err()
}

func anonymizeView(raw json.RawMessage, deleted map[string]bool) (json.RawMessage, error) {
	if len(deleted) == 0 {
		return raw, nil
	}
	var view map[string]json.RawMessage
	if err := json.Unmarshal(raw, &view); err != nil {
		return nil, err
	}
	for _, key := range []string{"seats", "players", "participants"} {
		if len(view[key]) == 0 {
			continue
		}
		var seats []map[string]json.RawMessage
		if err := json.Unmarshal(view[key], &seats); err != nil {
			return nil, err
		}
		for _, seat := range seats {
			var pid string
			if err := json.Unmarshal(seat["participant_id"], &pid); err != nil {
				continue
			}
			if deleted[pid] {
				seat["name"] = jsonBytes("已注销用户")
				delete(seat, "display_name")
			}
		}
		view[key] = jsonBytes(seats)
	}
	return json.Marshal(view)
}
