import { useEffect, useState } from 'react';
import { api, errorMessage, listFrom } from './api';
import { Badge, Button, Empty, Link, Loading, Notice, PageHeading, TileFace, formatName, modeName, statusName } from './components';
import { useResource } from './hooks';
import { normalizeSpectator } from './spectator';
import { normalizeParticipant } from './table-state';
import { SpectatorTable } from './Table';
import type { MatchRecord, ParticipantView, SpectatorView, User } from './types';
export function History({user}:{user?:User}) {const [mine,setMine]=useState(false);const r=useResource<unknown>(mine?'/v1/me/matches':'/v1/public/matches');const matches=listFrom<MatchRecord>(r.data,'matches');return <><PageHeading eyebrow="EVERY HAND TELLS A STORY" title="对局记录" action={<Link href="/statistics" className="button secondary">对局统计 ↗</Link>}>从已经打出的牌，回看一场对局。</PageHeading><div className="tabs history-tabs"><button className={!mine?'active':''} onClick={()=>setMine(false)}>公开对局</button><button className={mine?'active':''} disabled={!user} onClick={()=>setMine(true)}>我的对局</button></div><Notice error>{r.error}</Notice>{r.loading?<Loading text="读取对局记录…"/>:matches.length?<div className="history-list">{matches.map(m=><Link href={`/${mine?'replays':'matches'}/${m.id}`} className="history-card" key={m.id}><div className="history-symbol">牌</div><div><h3>{m.room_name??`对局 ${m.id.slice(0,8)}`}</h3><p>{modeName[m.mode]??m.mode} · {formatName[m.match_format]??m.match_format} · 国标 {m.ruleset_version}</p></div><div><Badge>{statusName[m.status]??m.status}</Badge><small>{m.created_at?new Date(m.created_at).toLocaleString('zh-CN'):''}</small></div><span>↗</span></Link>)}</div>:<Empty title={mine?'你还没有已记录的对局':'牌谱从第一场对局开始'} action={<Link href="/" className="button secondary">去大厅看看</Link>}>结束的牌局会保留弃牌记录；本人复盘需要验证参赛身份。</Empty>}</>;}
export function Replay({id,privateView,user}:{id:string;privateView:boolean;user?:User}) {const [frames,setFrames]=useState<(SpectatorView|ParticipantView)[]>([]);const [index,setIndex]=useState(0);const [hand,setHand]=useState(1);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [playing,setPlaying]=useState(false);const [hasMore,setHasMore]=useState(false);const [cursor,setCursor]=useState(0);const metadata=useResource<{match:MatchRecord}>(`/v1/public/matches/${encodeURIComponent(id)}`);const match=metadata.data?.match;
 useEffect(()=>{let active=true;const abort=new AbortController();setFrames([]);setIndex(0);setCursor(0);setLoading(true);setError('');setPlaying(false);if(privateView&&!user){setLoading(false);return()=>abort.abort();}void api<unknown>(`${privateView?'/v1/me':'/v1/public'}/matches/${encodeURIComponent(id)}/replay?hand_index=${hand}&after=0&limit=200`,{signal:abort.signal}).then(data=>{if(!active)return;const raw=listFrom<Record<string,unknown>>(data,'frames');setFrames(raw.map(f=>privateView?normalizeParticipant(f):normalizeSpectator(f)));setHasMore(raw.length===200);setCursor(typeof (data as {next_after?:unknown}).next_after==='number'?(data as {next_after:number}).next_after:raw.length);}).catch(e=>{if(active)setError(errorMessage(e));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;abort.abort();};},[id,privateView,hand,user?.id]);
 useEffect(()=>{if(!playing)return;const t=setInterval(()=>setIndex(i=>{if(i>=frames.length-1){setPlaying(false);return i;}return i+1;}),900);return()=>clearInterval(t);},[playing,frames.length]);
 async function more(){setLoading(true);try{const data=await api<unknown>(`${privateView?'/v1/me':'/v1/public'}/matches/${id}/replay?hand_index=${hand}&after=${cursor}&limit=200`);const raw=listFrom<Record<string,unknown>>(data,'frames');setFrames(f=>[...f,...raw.map(f=>privateView?normalizeParticipant(f):normalizeSpectator(f))]);setCursor(typeof (data as {next_after?:unknown}).next_after==='number'?(data as {next_after:number}).next_after:cursor+raw.length);setHasMore(raw.length===200);}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
 const current=frames[index];const totalHands=match?.match_format==='standard_16'?16:match?.match_format==='practice_4'?4:1;
 return <><PageHeading eyebrow={privateView?'MY REPLAY':'PUBLIC DISCARD REPLAY'} title={privateView?'本人视角复盘':'公开弃牌牌谱'} action={<Link href="/history" className="button secondary">全部对局</Link>}>{privateView?'仅显示本人获准查看的历史信息，不会切换到其他玩家的暗手。':'公开牌谱仅显示弃牌，结算后也不会揭露任何玩家的手牌。'}</PageHeading><Notice error>{error||metadata.error}</Notice>{privateView&&!user?<Notice>请先<Link href={`/auth/login?return_to=${encodeURIComponent(`/replays/${id}`)}`}>登录参赛账号</Link>。</Notice>:<><div className="replay-controls panel"><label>第 <select aria-label="选择盘数" value={hand} onChange={e=>setHand(Number(e.target.value))}>{Array.from({length:totalHands},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select> 盘</label><Button tone="secondary" disabled={!frames.length} onClick={()=>setPlaying(p=>!p)}>{playing?'暂停':'播放'}</Button><Button tone="quiet" disabled={index<=0} onClick={()=>{setPlaying(false);setIndex(i=>i-1);}}>上一步</Button><input type="range" aria-label="复盘进度" min={0} max={Math.max(0,frames.length-1)} value={index} onChange={e=>{setPlaying(false);setIndex(Number(e.target.value));}}/><Button tone="quiet" disabled={index>=frames.length-1} onClick={()=>{setPlaying(false);setIndex(i=>i+1);}}>下一步</Button><span>{frames.length?index+1:0} / {frames.length}</span></div>{current?<><SpectatorTable view={current}/>{privateView&&<section className="hand-panel"><h3>这一步的本人手牌</h3><div className="hand-tiles">{(current as ParticipantView).hand.map(t=><TileFace kind={t.kind} key={t.id}/>)}</div></section>}</>:loading?<Loading text="加载这一盘的记录…"/>:<Empty title="这盘暂时没有可用牌谱">可以选择其他盘数，或在比赛结束后重新查看。</Empty>}{hasMore&&<Button onClick={more} busy={loading}>加载后续记录</Button>}</>}</>;
}
