import { describe, expect, it } from 'vitest';
import { render } from '@testing-library/react';
import { normalizeSpectator } from './spectator';
import { SpectatorTable } from './Table';
const publicSnapshot = {match_id:'match_demo',status:'active',view:{view_policy:'spectator_discard_only@1',phase:'reaction',hand_index:1,seats:[{seat_id:0,participant_id:'p0',name:'东家'},{seat_id:1,participant_id:'p1',name:'南家'}],scores:[{participant_id:'p0',total:34},{participant_id:'p1',total:-18}],discards:[{discard_id:'d1',from_seat:0,kind:'1m',claimed:true},{discard_id:'d2',from_seat:1,kind:'7z',claimed:false}]}};
describe('spectator projection and rendering',()=>{
 it('maps the engine public DTO, preserving original claimed discards and stable player scores',()=>{const v=normalizeSpectator(publicSnapshot);expect(v.hand_index).toBe(1);expect(v.players).toEqual([{seat_id:0,seat_wind:0,name:'东家',score:34},{seat_id:1,seat_wind:0,name:'南家',score:-18}]);expect(v.discards.map(d=>[d.seat_id,d.tile,d.claimed])).toEqual([[0,'1m',true],[1,'7z',false]]);expect(JSON.stringify(v)).not.toContain('discard_id');});
 it('does not access concealed fields even if the API incorrectly includes them',()=>{const bad={...publicSnapshot,view:{...publicSnapshot.view}};for(const key of ['hand','wall','melds','flowers','result','legal_actions','trigger'])Object.defineProperty(bad.view,key,{enumerable:true,get:()=>{throw Error(`forbidden field read: ${key}`);}});const {container}=render(<SpectatorTable view={normalizeSpectator(bad)}/>);expect(container.querySelectorAll('.tile')).toHaveLength(2);expect(container.textContent).toContain('1萬');expect(container.textContent).toContain('白');expect(container.querySelectorAll('.hand-panel,.meld-row,.flowers-row')).toHaveLength(0);});
 it('hidden hands, supplementary draws and final reveals cannot influence spectator output',()=>{const expected=normalizeSpectator(publicSnapshot);for(let i=0;i<100;i++){const changed={...publicSnapshot,view:{...publicSnapshot.view,hand:[{tile_id:`secret-${i}`,kind:`${i%9+1}s`}],seats:publicSnapshot.view.seats.map(s=>({...s,hand:[`${i%9+1}p`],melds:[{type:'kong',tiles:['9m','9m','9m','9m']}],flowers:[{kind:'1h'}]})),result:{winner_hand:['9m'],fan_items:[{name:'secret-result'}]},wall:[i],drawn_tile_id:`secret-${i}`}};expect(normalizeSpectator(changed)).toEqual(expected);}});
 it('rejects nested private discard tiles and malformed kinds instead of accidentally unwrapping secrets',()=>{const v=normalizeSpectator({view:{discards:[{from_seat:0,tile:{tile_id:'secret',kind:'9m'}},{from_seat:1,kind:'<script>'},{from_seat:2,kind:'h2'}]}});expect(v.discards.map(d=>d.tile)).toEqual(['h2']);});
});
