import { useEffect, useState } from 'react';
import { commandID, errorMessage, post } from './api';
import { Badge, Button, Link, Loading, Notice, TileFace, tileLabel } from './components';
import type { ActionOption, ParticipantView, SpectatorView, User } from './types';
import { useTable } from './useTable';
const winds=['東','南','西','北'];
const actionNames:Record<string,string>={discard:'打出',chi:'吃',chow:'吃',pon:'碰',peng:'碰',pung:'碰',kong:'杠',gang:'杠',kan:'杠',ankan:'暗杠',concealed_kong:'暗杠',added_kong:'补杠',exposed_kong:'明杠',hu:'和牌',win:'和牌',tsumo:'自摸',ron:'和牌',pass:'过',replace_flower:'补花',flower:'补花',buhua:'补花'};
export function SpectatorTable({view,limit}:{view:SpectatorView;limit?:number}) { const discards=limit===undefined?view.discards:view.discards.slice(0,limit);return <div className="mahjong-table spectator-table" data-testid="spectator-table"><div className="table-center"><span className="table-logo">發</span><strong>公开弃牌</strong><span>第 {view.hand_index} 盘</span><small>{discards.length} 张已打出</small></div>{Array.from({length:Math.max(4,view.players.length)},(_,i)=>{const player=view.players.find(p=>p.seat_id===i);return <section key={i} className={`table-side side-${i}`} aria-label={`${winds[i]??i}位弃牌`}><div className="player-label"><span className="wind-badge">{winds[i]??i+1}</span><strong>{player?.name||`座位 ${i+1}`}</strong><span>{player?.score??0} 分</span></div><div className="discard-grid">{discards.filter(d=>d.seat_id===i).map((d,j)=><TileFace key={`${d.sequence}-${j}`} kind={d.tile} compact discarded={d.claimed}/>)}</div></section>;})}</div>; }
export function TablePage({id,spectator,user}:{id:string;spectator:boolean;user?:User}) {
 const {view,error,connected,refresh}=useTable(id,spectator);const [selected,setSelected]=useState('');const [busy,setBusy]=useState(false);const [actionError,setActionError]=useState('');const [recorded,setRecorded]=useState('');const [autoFlower,setAutoFlower]=useState(true);const [now,setNow]=useState(Date.now());
 const player=spectator?undefined:view as ParticipantView|undefined;const decision=player?.decision; const options=decision?.legal_actions??[];
 useEffect(()=>{setSelected('');setRecorded('');setActionError('');},[decision?.decision_id]);useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(t);},[]);
 async function act(option:ActionOption){if(!player||!decision||busy)return;setBusy(true);setActionError('');try{const result=await post<{status?:string;result?:string}>(`/v1/rooms/${encodeURIComponent(id)}/actions`,{command_id:commandID(),decision_id:decision.decision_id,option_id:option.option_id,window_id:player.window_id,hand_id:player.hand_id,match_id:player.match_id,seat_id:decision.seat_id,control_epoch:player.control_epoch,participant_id:player.participant_id,seat_assignment_version:player.seat_assignment_version});setRecorded(result.status==='applied'?'动作已执行':'动作已登记，等待服务端裁决。');setSelected('');}catch(e){setActionError(errorMessage(e));}finally{setBusy(false);}}
 useEffect(()=>{if(!spectator&&autoFlower&&!busy&&!recorded&&decision){const option=options.find(o=>['flower','replace_flower','buhua'].includes(o.type));if(option)void act(option);}},[decision?.decision_id,autoFlower]);
 const deadline=decision?.deadline_at||player?.deadline_at;const seconds=deadline?Math.max(0,Math.ceil((new Date(deadline).getTime()-now)/1000)):undefined;
 const selectedOption=options.find(o=>o.type==='discard'&&o.tile_id===selected);const ended=view&&['ended','completed','match_end','match_ended'].includes(view.phase||view.status||'');
 return <div className="table-page"><div className="table-toolbar"><Link href={`/rooms/${id}`} className="back-link">← 房间</Link><div><Badge live={connected}>{connected?'实时连接':'正在同步'}</Badge><span className="muted">国标麻将 · {spectator?'弃牌观战':'我的牌桌'}</span></div><Link href="/rules" className="text-button">规则说明 ↗</Link></div><Notice error>{error||actionError}</Notice>{spectator&&<div className="privacy-banner"><span>◉</span><div><strong>所有人都可以观战，只展示已经打出的牌。</strong><p>手牌、副露、花牌和终局成牌不会向观众展示。登录后观战也遵循相同边界。</p></div></div>}{!spectator&&!user&&<Notice error>请登录后访问本人牌桌。<Link href={`/auth/login?return_to=${encodeURIComponent(`/play/${id}`)}`}>前往登录</Link></Notice>}
 {!view?<Loading/>:spectator?<SpectatorTable view={view as SpectatorView}/>:<><div className="mahjong-table player-table"><div className="table-center"><span className="table-logo">發</span><strong>国标麻将</strong><span>第 {view.hand_index} 盘</span><small>{decision?`${seconds??'—'} 秒 · 轮到你`:'等待其他牌手'}</small></div>{Array.from({length:Math.max(4,player?.players.length??0)},(_,i)=>{const p=player?.players.find(p=>p.seat_id===i);return <section key={i} className={`table-side side-${i}`}><div className="player-label"><span className="wind-badge">{winds[i]}</span><strong>{p?.name||`座位 ${i+1}`}{i===player?.seat_id?' · 你':''}</strong><span>{p?.score??0} 分</span></div><div className="discard-grid">{view.discards.filter(d=>d.seat_id===i).map((d,j)=><TileFace key={j} kind={d.tile} compact discarded={d.claimed}/>)}</div>{p?.melds&&<div className="meld-row">{p.melds.map((m,j)=><div className="meld" key={j}><small>{actionNames[m.type]??m.type}</small>{m.tiles.map((t,k)=><TileFace key={k} kind={t.kind} compact/>)}</div>)}</div>}{p?.flowers&&p.flowers.length>0&&<div className="flowers-row">{p.flowers.map((f,j)=><TileFace kind={f} compact key={j}/>)}</div>}</section>;})}</div><section className="hand-panel"><div className="hand-heading"><div><span className="eyebrow">YOUR HAND</span><strong>{player?.players.find(p=>p.seat_id===player.seat_id)?.name??'我的手牌'}</strong></div><label className="check"><input type="checkbox" checked={autoFlower} onChange={e=>setAutoFlower(e.target.checked)}/>自动补花</label></div><div className="hand-tiles">{player?.hand.map(t=><TileFace kind={t.kind} key={t.id} selected={selected===t.id} onClick={()=>setSelected(t.id)} disabled={!options.some(o=>o.type==='discard'&&o.tile_id===t.id)||busy||!!recorded}/>)}</div><div className="action-bar">{selectedOption&&<Button busy={busy} disabled={!!recorded} onClick={()=>act(selectedOption)}>打出 {tileLabel(selectedOption.kind??player?.hand.find(t=>t.id===selected)?.kind??'')}</Button>}{options.filter(o=>o.type!=='discard').map(o=><Button key={o.option_id} busy={busy} disabled={!!recorded} tone={o.type==='pass'?'secondary':'primary'} onClick={()=>act(o)}>{actionNames[o.type]??o.type}{o.kind?` ${tileLabel(o.kind)}`:''}</Button>)}{!decision&&<span className="muted">{ended?'本场已结束':'等待当前响应窗口结束…'}</span>}{decision&&!selected&&!recorded&&options.some(o=>o.type==='discard')&&<span className="muted">先选一张牌，再确认打出。</span>}</div><Notice>{recorded}</Notice></section></>}
 {ended&&<section className="panel result-panel"><h2>对局已结束</h2><p>每一张弃牌，都留下了一次选择。</p><div className="result-scores">{view?.players.map(p=><div key={p.seat_id}><span>{p.name}</span><strong>{p.score>0?'+':''}{p.score}</strong></div>)}</div>{player?.outcome&&<Notice>本盘：{player.outcome.reason??'结算完成'}{player.outcome.fan!==undefined?`，非花 ${player.outcome.fan} 分`:''}</Notice>}<div className="room-actions"><Link href={`/rooms/${id}`} className="button primary">回到房间</Link>{view?.match_id&&<Link href={`/${spectator?'matches':'replays'}/${view.match_id}`} className="button secondary">查看{spectator?'公开弃牌记录':'本人复盘'}</Link>}</div></section>}
 <div className="table-footer"><span>观众永远只能看到弃牌 · 比赛由服务端统一裁决</span><button className="text-button" onClick={refresh}>重新同步 ↻</button>{!spectator&&<button className="text-button danger-text" onClick={async()=>{if(!window.confirm('确认在本手结束后退出？当前手将继续，剩余赛程提前结束。'))return;try{await post(`/v1/rooms/${id}/leave-after-hand`);setRecorded('已登记本手结束后退出。');}catch(e){setActionError(errorMessage(e));}}}>结束本手后退出</button>}</div></div>;
}
